<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-29T20:38:14 IST" name="Default suite" finished-at="2024-08-29T20:39:54 IST" duration-ms="100219">
    <groups>
    </groups>
    <test started-at="2024-08-29T20:38:14 IST" name="Default test" finished-at="2024-08-29T20:39:54 IST" duration-ms="100219">
      <class name="Login.Login">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Login.Login@5bf0d49]" started-at="2024-08-29T20:38:14 IST" name="setUp" finished-at="2024-08-29T20:38:54 IST" duration-ms="40055" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="cred()[pri:0, instance:Login.Login@5bf0d49]" started-at="2024-08-29T20:38:54 IST" name="cred" finished-at="2024-08-29T20:38:55 IST" duration-ms="477" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cred -->
        <test-method signature="Selectcompany()[pri:0, instance:Login.Login@5bf0d49]" started-at="2024-08-29T20:38:55 IST" name="Selectcompany" finished-at="2024-08-29T20:38:57 IST" depends-on-methods="Login.Login.cred" duration-ms="2622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Selectcompany -->
        <test-method signature="Tripss()[pri:0, instance:Login.Login@5bf0d49]" started-at="2024-08-29T20:38:57 IST" name="Tripss" finished-at="2024-08-29T20:38:58 IST" depends-on-methods="Login.Login.Selectcompany" duration-ms="1006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tripss -->
        <test-method signature="CheckBox()[pri:0, instance:Login.Login@5bf0d49]" started-at="2024-08-29T20:38:58 IST" name="CheckBox" finished-at="2024-08-29T20:39:54 IST" depends-on-methods="Login.Login.Tripss" duration-ms="55983" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to select the checkbox: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //div[@id='tripsComponent']//following-sibling::div[@class='row my-4']//child::table[@id='_trips_content_table']//child::tbody//tr//td[contains(text(),'Trip 15532')]//parent::tr//descendant::span[@class='e-frame e-icons']' (tried for 20 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to select the checkbox: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //div[@id='tripsComponent']//following-sibling::div[@class='row my-4']//child::table[@id='_trips_content_table']//child::tbody//tr//td[contains(text(),'Trip 15532')]//parent::tr//descendant::span[@class='e-frame e-icons']' (tried for 20 second(s) with 500 milliseconds interval)
at org.testng.Assert.fail(Assert.java:99)
at LoginCred.Trips.FTrip(Trips.java:77)
at Login.Login.CheckBox(Login.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckBox -->
        <test-method signature="log()[pri:0, instance:Login.Login@5bf0d49]" started-at="2024-08-29T20:39:54 IST" name="log" finished-at="2024-08-29T20:39:54 IST" depends-on-methods="Login.Login.CheckBox" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Login.log()[pri:0, instance:Login.Login@5bf0d49] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Login.log()[pri:0, instance:Login.Login@5bf0d49] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- log -->
        <test-method signature="openurl()[pri:0, instance:Login.Login@5bf0d49]" started-at="2024-08-29T20:39:54 IST" name="openurl" finished-at="2024-08-29T20:39:54 IST" depends-on-methods="Login.Login.log" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Login.openurl()[pri:0, instance:Login.Login@5bf0d49] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Login.openurl()[pri:0, instance:Login.Login@5bf0d49] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openurl -->
      </class> <!-- Login.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
